name: Weekly Issue Creator

on:
  schedule:
    - cron: "0 13 * * 0"  # 매주 일요일 저녁 10시 (한국 시간 기준)
  workflow_dispatch:  # 수동 실행 가능

jobs:
  create-issue:
    runs-on: ubuntu-latest
    permissions:
      issues: write  # 이슈 생성 권한 추가
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fetch latest issue number
        id: fetch_latest_issue
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          API_URL="https://api.github.com/repos/DShomin/weekly-archive/issues?state=all&per_page=1"

          API_RESPONSE=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" "$API_URL")

          echo "API RESPONSE: $API_RESPONSE"  # Debugging 출력

          LATEST_ISSUE=$(echo "$API_RESPONSE" | jq -r '.[0].title')
          echo "LATEST_ISSUE=$LATEST_ISSUE"

          # 가장 마지막 회차 숫자만 추출
          LAST_COUNT=$(echo "$LATEST_ISSUE" | grep -oE '[0-9]+회차' | grep -oE '[0-9]+')

          if [[ -n "$LAST_COUNT" ]]; then
            NEXT_COUNT=$((LAST_COUNT + 1))
          else
            NEXT_COUNT=1
          fi

          echo "NEXT_COUNT=$NEXT_COUNT" >> $GITHUB_ENV

      - name: Generate Issue Title
        id: title
        run: |
          # 다음 일요일 날짜 계산 (두 가지 방식 지원)
          DATE=$(date -u -d "+7 days" +"%y%m%d" 2>/dev/null || date -v+7d +"%y%m%d")
          TITLE="[$DATE] Weekly archive - ${NEXT_COUNT}회차"
          echo "Generated title: $TITLE"  # 로그 출력 (디버깅용)
          echo "ISSUE_TITLE=$TITLE" >> $GITHUB_ENV

      - name: Create GitHub Issue
        env:
          GITHUB_TOKEN: ${{ github.token }}
          ISSUE_TITLE: ${{ env.ISSUE_TITLE }}
        run: |
          API_URL="https://api.github.com/repos/DShomin/weekly-archive/issues"
          
          RESPONSE=$(curl -X POST \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            "$API_URL" \
            -d '{
              "title": "'"$ISSUE_TITLE"'",
              "body": "이번 주의 주요 업데이트 내용을 기록하세요.",
              "labels": ["weekly", "automation"]
            }')
          
          echo "API Response: $RESPONSE"
          
          # 오류 확인
          if echo "$RESPONSE" | grep -q "error"; then
            echo "Error creating issue"
            exit 1
          fi